name: my second workflow

on:
  push

jobs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: list files
      run: ls -lrta

    - name: shell execute
      run: ./shell-script.sh
      
