name: first action

on: 
    workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v5

            - name: welcome message
              run: echo "My first action"
            
            - name: list files
              run: |
                ls
                cat README.md
            
            - name: Install cowsay and Generate ASCII artwork
              run: |
                sudo apt-get install cowsay -y
                cowsay -f dragon "Run for cover, I am dragon.. RAWR" >> dragon.txt
                ls
            
            - name: show the content of dragon.txt
              run: |
                ls -lrta
                cat dragon.txt

