name: Invoke shell script in workflow

on:
  workflow_dispatch:
jobs:
    shelljob:
        runs-on: ubuntu-24.04
        steps:
            - name: checkout repo
              uses: actions/checkout@v5

            - name: Invoke shell script in workflow
              run: |
                chmod +x shell-script.sh
                ./shell-script.sh
    