name: multi job action

on: 
    push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6
            
            - name: install cowsay and run
              run: |
                sudo apt-get install cowsay -y
                cowsay -f dragon "I am dragon...run for ur lives ... " >> dragon.txt
    
            - name: Upload the artifact dragon.txt
              uses: actions/Upload-artifact@v7
              with:
                path: dragon.txt
                archive: false
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v7
              with:
                name: dragon.txt
                
            - name: verify the file existence
              run: |
                ls -lrta
                grep -i "dragon" dragon.txt
    
    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v7
              with:
                name: dragon.txt

            - name: read file
              run: cat dragon.txt

            - name: deployig
              run: echo "Deployig ..."