name: working with variables and secrets

on:
    push
env:
    dockerimagename: "testimage"
    dockerimagetag: "1.0.0"

jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: build docker
              run: echo "docker build ${{vars.DOCKERUSERNAME}}/${{env.dockerimagename}}:${{env.dockerimagetag}}"
    
    docker-deploy:
        needs: docker-build
        runs-on: ubuntu-latest
        steps:
            - name: docker deploy
              run: |
                echo docker login --username=$dockerusername --password=${{secrets.DOCKERPASSWORD}}
                echo "Deploying docker image ${{vars.DOCKERUSERNAME}}/${{env.dockerimagename}}:${{env.dockerimagetag}}"
                echo "Docker user pwd: ${{secrets.DOCKERPASSWORD}}"