name: working with variables and secrets

on:
    push
env:
    dockerusername: "testusername"
    dockerimagename: "testimage"
    dockerimagetag: "1.0.0"

jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: build docker
              run: echo "docker build ${{env.dockerusername}}/${{env.dockerimagename}}:${{env.dockerimagetag}}"
    
    docker-deploy:
        needs: docker-build
        runs-on: ubuntu-latest
        steps:
            - name: docker deploy
              env:
                dockeruserpwd: "test1234"
              run: |
                echo docker login --username=$dockerusername --password=${{env.dockeruserpwd}}
                echo "Deploying docker image ${{env.dockerusername}}/${{env.dockerimagename}}:${{env.dockerimagetag}}"
                echo "Docker user pwd: ${{env.dockeruserpwd}}"