name: github context details

on:
    push:
    workflow_dispatch:
        
jobs:
    github_context:
        runs-on: ubuntu-latest
        steps:
            - name: get github context
              env:
                GITHUB_CONTEXT: ${{toJson(github)}}
              run: echo $GITHUB_CONTEXT

            - name: get secreat context
              env:
                secret_con: ${{toJson(secrets)}}
              run: echo $secret_con