name: Matrix config testing

on:
    - push
    - workflow_dispatch

jobs:
    docker-details:
        runs-on: ubuntu-latest
        steps:
            - name: docker info
              run: docker info
            
            - name: docker run image
              run: docker run hello-world