name: Test trigger workflow via events

on:
  workflow_dispatch:
 
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run:  echo docker build --username ${{vars.DOCKERUSERNAME}} with --password ${{secrets.DOCKERPASSWORD}}

  docker-deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: deploy docker image
        run: echo docker run --username ${{vars.DOCKERUSERNAME}} with --password ${{secrets.DOCKERPASSWORD}}