name: Test trigger workflow via events

on:
  workflow_dispatch:
 
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run:  |
          echo docker build --username ${{vars.DOCKERUSERNAME}} with --password ${{secrets.DOCKERPASSWORD}}
          echo $GITHUB_CONTEXT

  docker-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docker-build
    concurrency:
      group: deployment
      cancel-in-progress: true
    steps:
      - name: deploy docker image
        timeout-minutes: 1
        run: |
          echo docker run --username ${{vars.DOCKERUSERNAME}} with --password ${{secrets.DOCKERPASSWORD}}
          sleep 6000
